kind: pipeline
name: ci-cd
type: docker

steps:
  - name: restore-cache
    image: meltwater/drone-cache
    pull: true
    settings:
      backend: filesystem
      restore: true
      cache_key: composer-npm-cache
      archive_format: gzip
      mount:
        - vendor
        - node_modules
    volumes:
      - name: cache
        path: /tmp/cache

  - name: prepare-environment
    image: laravelsail/php83-composer
    depends_on:
      - restore-cache
    commands:
      - apt-get update && apt-get install -y unzip git zip curl libzip-dev libpng-dev libonig-dev libxml2-dev libgd-dev libicu-dev
      - docker-php-ext-install intl gd
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - composer install --prefer-dist --no-interaction
      - npm ci

  - name: pint
    image: laravelsail/php83-composer
    depends_on:
      - prepare-environment
    commands:
      - apt-get update && apt-get install -y unzip git zip curl libzip-dev libpng-dev libonig-dev libxml2-dev libgd-dev libicu-dev
      - docker-php-ext-install intl gd
      - composer install --prefer-dist --no-interaction
      - ./vendor/bin/pint

  - name: phpstan
    image: laravelsail/php83-composer
    depends_on:
      - prepare-environment
    commands:
      - composer install --prefer-dist --no-interaction
      - ./vendor/bin/phpstan analyse

  - name: pest-tests
    image: laravelsail/php83-composer
    depends_on:
      - prepare-environment
    environment:
      APP_ENV: testing
      APP_KEY:
        from_secret: APP_KEY
    commands:
      - composer install --prefer-dist --no-interaction
      - php artisan test --parallel

  - name: build-assets
    image: node:20
    depends_on:
      - pint
      - phpstan
      - pest-tests
    commands:
      - npm ci
      - npm run build

  - name: merge-to-master
    image: alpine
    depends_on:
      - build-assets
    environment:
      GITEA_TOKEN:
        from_secret: GITEA_TOKEN
    commands:
      - apk add git
      - git config --global user.name "Tor Rivera"
      - git config --global user.email "tor@trivera.net"
      - git remote set-url origin https://oauth2:$GITEA_TOKEN@gitea.torriv.synology.me/torriv/nybpa.git
      - git fetch origin
      - git checkout master || git checkout -b master
      - git merge --no-edit devtest
      - git push origin master

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: true
    depends_on:
      - build-assets
    settings:
      backend: filesystem
      rebuild: true
      cache_key: composer-npm-cache
      archive_format: gzip
      mount:
        - vendor
        - node_modules
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    temp: {}

trigger:
  branch:
    include:
      - devtest
