kind: pipeline
name: ci-cd
type: docker

steps:
  - name: prepare-environment
    image: laravelsail/php83-composer
    commands:
      - apt-get update && apt-get install -y unzip git zip curl libzip-dev libpng-dev libonig-dev libxml2-dev libgd-dev libicu-dev
      - docker-php-ext-install intl gd
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - composer install --prefer-dist --no-interaction
      - npm ci

  - name: build-assets
    image: node:20
    commands:
      - npm ci
      - npm run build

  - name: phpstan
    image: laravelsail/php83-composer
    depends_on:
      - build-assets
    environment:
      PHP_MEMORY_LIMIT: 512M
    commands:
      - ./vendor/bin/phpstan analyse --memory-limit=512M || true

  - name: optimize-autoloader
    image: laravelsail/php83-composer
    depends_on:
      - phpstan
    commands:
      - composer install --optimize-autoloader --no-dev

  - name: cache-configuration-routes-views
    image: laravelsail/php83-composer
    depends_on:
      - optimize-autoloader
    commands:
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache

  - name: optimize
    image: laravelsail/php83-composer
    depends_on:
      - cache-configuration-routes-views
    commands:
      - php artisan optimize

  - name: pest-tests
    image: laravelsail/php83-composer
    environment:
      APP_ENV: testing
      APP_KEY:
        from_secret: APP_KEY
      APP_DEBUG: true
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
    commands:
      - php artisan test --parallel

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: true
    depends_on:
      - pest-tests
    settings:
      backend: filesystem
      rebuild: true
      cache_key: composer-npm-cache
      archive_format: gzip
      mount:
        - path: /tmp/cache/nybpa/composer-npm-cache/vendor
        - path: /tmp/cache/nybpa/composer-npm-cache/node_modules
    volumes:
      - name: cache
        path: /tmp/cache

trigger:
  branch:
    include:
      - devtest
