name: Deploy Laravel Application

on:
  push:
    branches: [devtest]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, redis

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader -v

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install NPM dependencies and build assets
        run: |
          npm ci
          npm run build

      - name: Cache Laravel config, routes, views, filament
        run: |
          php artisan optimize
          php artisan filament:optimize

      - name: Run tests
        run: |
          php artisan config:clear
          php artisan test --parallel

      - name: Commit built assets and Laravel cache
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "ci@nybpa.no"
          git add public/build
          git commit -m "🚀 Auto-commit: bygde frontend-assets og cache-filer" || echo "Ingenting å committe"
          git push origin HEAD:master
        env:
          GIT_AUTHOR_NAME: CI Bot
          GIT_AUTHOR_EMAIL: ci@nybpa.no

      - name: Notify Discord – success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"✅ CI-kjøring for *nybpa* fullført og pushet til `master`!"}' \
               $DISCORD_WEBHOOK
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord – failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"❌ CI feilet for *nybpa*. Sjekk loggene!"}' \
               $DISCORD_WEBHOOK
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

#
#      # Cache-konfigurasjon, ruter og visninger
#      - name: Cache configuration, routes, and views
#        run: |
#          php artisan config:cache
#          php artisan route:cache
#          php artisan view:cache
#
#      # Optimaliser Laravel
#      - name: Optimize
#        run: php artisan optimize
#
#      # Deploy til server
#      - name: Deploy to server
#        run: |
#          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /var/www/your-app && git pull origin master && composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan optimize"
