name: Prepare and Build Project
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:8.3-cli  # Bruker php:8.3-cli for å sikre at vi bruker PHP 8.3
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Installer PHP 8.3 og nødvendige avhengigheter
      - name: Install PHP 8.3 and dependencies
        run: |
          apt-get update -yqq
          apt-get install -yqq apt-utils autoconf build-essential  # Installer nødvendige verktøy
          apt-get install -yqq git libpq-dev libzip-dev curl libpng-dev libonig-dev libxml2-dev libicu-dev libgd-dev
          docker-php-ext-install pdo_mysql zip intl gd  # Installer PHP-utvidelser

          # Installer Node.js v16.x og bekreft versjon
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs
          node --version  # Bekrefter at node er installert
          npm --version  # Bekrefter at npm er installert

          # Installer Composer
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --verbose

          # Installer Node.js-avhengigheter
          npm ci --verbose

      # Kjør PHPStan
      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit=1024M || true

      # Bygg frontend assets
      - name: Build frontend assets
        run: npm run build

      # Kjør tester
      - name: Run tests
        run: php artisan test --parallel

      # Cache-konfigurasjon, ruter og visninger
      - name: Cache configuration, routes, and views
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Optimaliser Laravel
      - name: Optimize
        run: php artisan optimize

      # Deploy til server
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /var/www/your-app && git pull origin master && composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan optimize"
