name: Prepare and Build Project
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: php:8.4-cli  # Bruker php:8.4-cli for å få tilgang til docker-php-ext-install
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update -yqq
          apt-get install -yqq apt-utils autoconf build-essential  # Installer nødvendige verktøy
          apt-get install -yqq git libpq-dev libzip-dev curl libpng-dev libonig-dev libxml2-dev libicu-dev libgd-dev
          docker-php-ext-install pdo_mysql zip intl gd  # Installer PHP-utvidelser
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs
          npm --version  # Bekrefter at npm er installert
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --verbose
          npm ci --verbose

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --memory-limit=1024M || true

      - name: Build frontend assets
        run: npm run build

      - name: Run tests
        run: php artisan test --parallel

      - name: Cache configuration, routes, and views
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Optimize
        run: php artisan optimize

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /var/www/your-app && git pull origin master && composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan optimize"
