name: Deploy Laravel Application

on:
  push:
    branches: [devtest]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, redis

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader -v

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install NPM dependencies and build assets
        run: |
          npm ci
          npm run build

      - name: Cache Laravel config, routes, views, filament
        run: |
          php artisan optimize
          php artisan filament:optimize

      - name: Run Pint (Laravel code style)
        run: ./vendor/bin/pint --test

      - name: Run Larastan (PHPStan)
        run: ./vendor/bin/phpstan analyse

      - name: Run tests
        run: |
          php artisan config:clear
          php artisan test --parallel

      - name: Notify Discord – success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"✅ CI-kjøring for *nybpa* fullført og pushet til `master`!"}' \
               $DISCORD_WEBHOOK
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord – failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"❌ CI feilet for *nybpa*. Sjekk loggene!"}' \
               $DISCORD_WEBHOOK
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
