name: Deploy Laravel Application

on:
  push:
    branches: [devtest]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, redis

      - name: Install Composer dependencies
        run: |
          composer install --optimize-autoloader -v
          echo "Composer install fullført"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install NPM dependencies and build assets
        run: |
          npm ci
          npm run build

      - name: Run tests
        run: |
          php artisan config:clear
          php artisan test --parallel

      - name: Notify Discord – success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"✅ CI-kjøring for *nybpa* fullført uten feil!"}' \
               $DISCORD_WEBHOOK
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify Discord – failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"❌ CI-kjøring for *nybpa* feilet. Undersøk loggene."}' \
               $DISCORD_WEBHOOK
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

#
#      # Cache-konfigurasjon, ruter og visninger
#      - name: Cache configuration, routes, and views
#        run: |
#          php artisan config:cache
#          php artisan route:cache
#          php artisan view:cache
#
#      # Optimaliser Laravel
#      - name: Optimize
#        run: php artisan optimize
#
#      # Deploy til server
#      - name: Deploy to server
#        run: |
#          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /var/www/your-app && git pull origin master && composer install --no-dev --optimize-autoloader && php artisan migrate --force && php artisan optimize"
